Optimize omr-mtu script

diff --git a/openmptcprouter/files/bin/omr-mtu b/openmptcprouter/files/bin/omr-mtu
--- a/openmptcprouter/files/bin/omr-mtu
+++ b/openmptcprouter/files/bin/omr-mtu
@@ -1,21 +1,35 @@
 #!/bin/sh
 
-PKT_SIZE=1472
 INTERFACE="$1"
 HOSTNAME="$2"
 
-#count=$(ping -q -w 1 -M do -c 1 -s $PKT_SIZE -I $INTERFACE $HOSTNAME | grep -cE 'Message too long|100% packet loss')
-#count=$(ping -B -w 1 -M do -c 1 -s $PKT_SIZE -I $INTERFACE $HOSTNAME 2>&1 | grep -c 'Message too long')
-count=$(ping -B -w 2 -M do -c 3 -s $PKT_SIZE -I $INTERFACE $HOSTNAME 2>&1 | grep -cE 'Message too long|100% packet loss')
+_too_big() {
+	count=$(ping -B -w 2 -M do -c 3 -s "$1" -I "$INTERFACE" "$HOSTNAME" 2>&1 | grep -cE 'Message too long|100% packet loss')
+	[ "$count" -ge 1 ]
+}
 
-while [ $count -ge 1 ]; do
-	PKT_SIZE=$((PKT_SIZE - 1))
-	if [ "$PKT_SIZE" -lt "1252" ]; then 
-		exit 0
+lo=1252
+hi=1472
+
+# Fast path: max size already works
+if ! _too_big $hi; then
+	printf "%d" $((hi + 28))
+	exit 0
+fi
+
+# Nothing in our range works
+if _too_big $lo; then
+	exit 0
+fi
+
+# Binary search: invariant: lo works, hi fails
+while [ $((hi - lo)) -gt 1 ]; do
+	mid=$(( (lo + hi) / 2 ))
+	if _too_big "$mid"; then
+		hi=$mid
+	else
+		lo=$mid
 	fi
-	#count=$(ping -q -w 1 -M do -c 1 -s $PKT_SIZE -I $INTERFACE $HOSTNAME | grep -cE 'Message too long|100% packet loss')
-	#count=$(ping -B -w 1 -M do -c 1 -s $PKT_SIZE -I $INTERFACE $HOSTNAME 2>&1 | grep -c 'Message too long')
-	count=$(ping -B -w 2 -M do -c 3 -s $PKT_SIZE -I $INTERFACE $HOSTNAME 2>&1 | grep -cE 'Message too long|100% packet loss')
 done
 
-printf "$((PKT_SIZE + 28))"
+printf "%d" $((lo + 28))
